# Global Makefile
#
# Sets up rules for building, and includes Makefiles from all targets
#
# Copyright 2008-2013 Efraim Feinstein
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/
#
#
# Possibilities of targets:
# all - makes code targets
# schema - schema and schema documentation for the TEI extension (places results in doc/jlp by default)
# odddoc - a synonym for schema
# xsltdoc - documentation for the XSLT code (places result in doc/code)
# dist - make a .tar.gz for distribution
#
# db-install - install database to $(EXIST_INSTALL_DIR)
# db-uninstall - remove $(EXIST_INSTALL_DIR)
# db-sync DBAPASS=<database password> - synchronize code, data, and common from the development working copy to a running database; 
# db-syncclean - clean the __contents__.xml files left by syncing the database 
# 

# Local changes to variables should go in Makefile.local
# Any variable set in this file may be overridden by a setting in Makefile.local
-include Makefile.local

# admin password: CHANGE IT(!) in Makefile.local
ADMINPASSWORD ?= password

# dependencies from make depend go in this file, which is generated by make depend
-include Makefile.depend

# assumes the directory structure of the repository
TOPDIR ?= .
CODETAG ?= .
DATATAG ?= .
TEXTTAG ?= .
ODDTAG ?= .
COMMONTAG ?= .
LIBTAG ?= .
SETUPTAG ?= .

CODEDIR ?= $(TOPDIR)/$(CODETAG)/code
DATADIR ?= $(TOPDIR)/$(DATATAG)/data
TEXTDIR ?= $(TOPDIR)/$(TEXTTAG)/text
ODDDIR ?= $(TOPDIR)/$(ODDTAG)/schema
LIBDIR ?= $(TOPDIR)/$(LIBTAG)/lib
SETUPDIR ?= $(TOPDIR)/$(SETUPTAG)/setup
COMMONDIR ?= $(TOPDIR)/$(COMMONTAG)/common
DOCDIR ?= $(TOPDIR)/doc
DBDIR ?= $(TOPDIR)/db
TEMPDIR ?= $(TOPDIR)/tmp

# java home... you will probably have to set this in Makefile.local
JAVA_HOME ?= /usr/lib/jvm/java-6-openjdk/

# everything that can be made depends on these files
ALL_DEPEND=Makefile $(COMMONDIR)/catalog.xml

# code documentation:
# when you change this directory, you also need to change the path pointed to by
# the TargetDirectory element in XSLTDocConfig.xml
CODEDOCDIR ?= $(DOCDIR)/code
# TEI extension documentation:
TEIDOCDIR ?= $(DOCDIR)/jlp

# root directory (used only for calls to Java from cygwin)
ROOTDIR ?= 

# XSLT options: 
#	for saxon v8.9, there are none.  For version 9+, use -ext:on to allow creation of files
XSLTLOCALOPTIONS ?=
XSLTOPTIONS ?= -ext:on -x:org.apache.xml.resolver.tools.ResolvingXMLReader -y:org.apache.xml.resolver.tools.ResolvingXMLReader -r:org.apache.xml.resolver.tools.CatalogResolver $(XSLTLOCALOPTIONS) 
# TeXML options: -e utf8 allows utf-8 encoded input
TEXMLOPTIONS ?= -e utf8
# Roma options: 
#	--doc makes TEI documentation, 
#	--docpdf makes PDF documentation (broken!)
#	--dochtml makes HTML documentation
ROMAOPTIONS ?= --xsl=$(LIBDIR)/tei/Stylesheets --localsource=`absolutize $(LIBDIR)/tei/P5/p5subset.xml` --doc --dochtml 

# XML validator options
RELAXNGOPTIONS ?= $(TEIDOCDIR)/jlptei.rng

# default eXist install directory
EXIST_INSTALL_DIR ?= /usr/local/opensiddur

# paths to programs:
LOCALPATH ?= /usr/local
EXIST_INSTALL_JAR ?= $(LIBDIR)/exist/installer/eXist-db-setup-2.0RC2-rev$(EXIST_REV).jar
EXISTCLIENT ?= $(EXIST_INSTALL_DIR)/bin/client.sh
EXISTBACKUP ?= java -Dexist.home=$(EXIST_INSTALL_DIR) -jar $(EXIST_INSTALL_DIR)/start.jar org.exist.backup.Main 

RESOLVERPATH ?= $(LIBDIR)/resolver-1.2.jar
CP ?= /bin/cp
JAVAOPTIONS ?=
SAXONJAR ?= $(LIBDIR)/saxonhe-9.2.1.5.jar
# CPSEP=classpath separator - : on Unix, ; on Windows
JCLASSPATH ?= "$(RESOLVERPATH):$(SAXONJAR):$(LIBDIR)"
SAXONCLASS ?= net.sf.saxon.Transform
XSLT ?= java $(JAVAOPTIONS) -cp "$(JCLASSPATH)" -Dxml.catalog.files=$(LIBDIR)/catalog.xml -Dxml.catalog.verbosity=1 $(SAXONCLASS) $(XSLTOPTIONS) 
XSLTDOC ?= $(LIBDIR)/XSLTDoc/xsl/xsltdoc.xsl
TEIROMA ?= $(LIBDIR)/tei/Roma/roma2.sh $(ROMAOPTIONS)
RELAXNG ?= $(LIBDIR)/jing $(RELAXNGOPTIONS)

# changes for Cygwin path (experimental, not necessarily maintained!)
-include Makefile.cygwin

# directories for externals
XSPECDIR = $(LIBDIR)/xspec
XSPECREPO = http://xspec.googlecode.com/svn/trunk/

XSLTFORMSDIR = $(LIBDIR)/xsltforms
XSLTFORMSREPO = https://xsltforms.svn.sourceforge.net/svnroot/xsltforms
XSLTFORMS_REVISION ?= -r 565

XSLTDOCDIR = $(LIBDIR)/XSLTDoc
XSLTDOCREPO = https://xsltdoc.svn.sourceforge.net/svnroot/xsltdoc/trunk/xsltdoc

TEIDIR = $(LIBDIR)/tei
TEIREPO = https://tei.svn.sourceforge.net/svnroot/tei/trunk
TEI_REVISION ?= -r 11440

EXISTSRCDIR = $(LIBDIR)/exist
EXISTSRCREPO = svn://svn.code.sf.net/p/exist/code/trunk/eXist
# lock eXist to a given revision
EXIST_REV ?= 18233
EXIST_REVISION ?= -r $(EXIST_REV)

all:  code input-conversion xsltdoc odddoc lib

include $(TEXTDIR)/Makefile
include $(CODEDIR)/Makefile
include $(ODDDIR)/Makefile
include $(LIBDIR)/Makefile

XSLTDOC_CFGFILE ?= XSLTDocConfig.xml

$(TEMPDIR):
	mkdir $(TEMPDIR)

.PHONY: schema schema-clean
schema: $(DBDIR)/schema jlptei-schema transliteration-schema contributor-schema bibliography-schema annotation-schema linkage-schema conditional-schema
	cp schema/build/jlptei.rnc $(DBDIR)/schema
	cp schema/build/linkage.rnc $(DBDIR)/schema
	cp schema/build/contributor.rnc $(DBDIR)/schema
	cp schema/build/bibliography.rnc $(DBDIR)/schema
	cp schema/build/annotation.rnc $(DBDIR)/schema
	cp schema/build/conditional.rnc $(DBDIR)/schema
	cp schema/build/*.xsl2 $(DBDIR)/schema
	cp schema/transliteration.rnc $(DBDIR)/schema
	cp schema/access.rnc $(DBDIR)/schema
	cp schema/group.rnc $(DBDIR)/schema

schema-clean: schema-build-clean
	rm -fr $(DBDIR)/schema

.PHONY: clean
clean: xsltdoc-clean schema-clean code-clean input-conversion-clean db-clean db-syncclean clean-hebmorph clean-hebmorph-lucene dist-clean-exist setup-clean

$(DBDIR)/common: $(DBDIR)/code

RSYNC_EXCLUDE=--exclude=.svn --exclude=~*

$(DBDIR)/code: code
	#svn update $(DBDIR)
	find $(DBDIR) -name __contents__.xml | xargs rm -f
	rsync $(RSYNC_EXCLUDE) -a --delete group $(DBDIR)
	rsync $(RSYNC_EXCLUDE) -a --delete code $(DBDIR)


$(DBDIR)/schema:
	mkdir -p $(DBDIR)/schema

IZPACK:=$(shell $(LIBDIR)/absolutize $(LIBDIR)/IzPack)

# build eXist (what dependencies should this have?)
# made dependent on the Makefile because that is where the revision is set.
# It will cause too many remakes, but better than not remaking at all
$(EXIST_INSTALL_JAR): Makefile
	cp setup/exist-extensions-local.build.properties $(LIBDIR)/exist/extensions/local.build.properties
	cd $(LIBDIR)/exist && \
		JAVA_HOME=$(JAVA_HOME) \
		./build.sh svn-download
	cd $(LIBDIR)/exist && \
		JAVA_HOME=$(JAVA_HOME) \
		./build.sh installer -Dizpack.dir=$(IZPACK) -Dinclude.module.scheduler=true

.PHONY: build-exist clean-exist dist-clean-exist
build-exist: $(EXIST_INSTALL_JAR)

clean-exist:
	rm -f $(EXIST_INSTALL_JAR)

dist-clean-exist:
	cd $(LIBDIR)/exist && \
		JAVA_HOME=$(JAVA_HOME) \
		./build.sh clean

.PHONY: build-hebmorph build-hebmorph-lucene clean-hebmorph clean-hebmorph-lucene
build-hebmorph: $(LIBDIR)/hebmorph/java/hebmorph/build/distribution/hebmorph.jar

$(LIBDIR)/hebmorph/java/hebmorph/build/distribution/hebmorph.jar:
	cd $(LIBDIR)/hebmorph/java/hebmorph/ && \
    ant jar

clean-hebmorph:
	cd $(LIBDIR)/hebmorph/java/hebmorph/ && \
    ant clean

build-hebmorph-lucene: build-hebmorph $(LIBDIR)/hebmorph/java/lucene.hebrew/build/distribution/lucene.hebrew.jar 

$(LIBDIR)/hebmorph/java/lucene.hebrew/build/distribution/lucene.hebrew.jar:
	#cp $(LIBDIR)/exist/extensions/indexes/lucene/lucene*.jar $(LIBDIR)/hebmorph/java/lucene.hebrew/lib
	cd $(LIBDIR)/hebmorph/java/lucene.hebrew/ && ant jar

clean-hebmorph-lucene:
	cd $(LIBDIR)/hebmorph/java/lucene.hebrew/ && ant clean
	rm -f $(LIBDIR)/hebmorph/java/lucene.hebrew/build/distribution/lucene.hebrew.jar 

# Install a copy of the eXist database
.PHONY: db-install db-install-nonet db-install-wlc db-uninstall db-sync db-syncclean installer patches lucene-install copy-files copy-libs setup-password
db-install: submodules svn-exist code $(EXIST_INSTALL_JAR) build-hebmorph-lucene installer patches lucene-install db setup-password copy-files copy-libs   

#installer that does not rely on the presence of a network. 
db-install-nonet: code $(EXIST_INSTALL_JAR) build-hebmorph-lucene installer patches lucene-install db-nonet setup-password copy-files copy-libs
	@echo "Done."
	touch $(EXIST_INSTALL_DIR)/EXIST.AUTOINSTALLED

# copy libraries that are stored in the filesystem
copy-libs:
	mkdir -p $(EXIST_INSTALL_DIR)/webapp/aloha
	cp -r $(LIBDIR)/aloha/src/* $(EXIST_INSTALL_DIR)/webapp/aloha

installer: $(EXIST_INSTALL_JAR)
	expect $(SETUPDIR)/install.exp "$(EXIST_INSTALL_JAR)" "$(EXIST_INSTALL_DIR)" "$(ADMINPASSWORD)"

patches:
	$(XSLT) -s $(EXIST_INSTALL_DIR)/conf.xml -o $(EXIST_INSTALL_DIR)/conf.xml $(SETUPDIR)/setup-conf-xml.xsl2
	$(XSLT) -s $(EXIST_INSTALL_DIR)/mime-types.xml -o $(EXIST_INSTALL_DIR)/mime-types.xml $(SETUPDIR)/setup-mime-types.xsl2
	$(XSLT) -s $(EXIST_INSTALL_DIR)/webapp/WEB-INF/controller-config.xml -o $(EXIST_INSTALL_DIR)/webapp/WEB-INF/controller-config.xml $(SETUPDIR)/setup-controller-config-xml.xsl2
	-patch -Nd $(EXIST_INSTALL_DIR)/tools/jetty/etc < $(SETUPDIR)/jetty.xml.patch

lucene-install: installer $(EXIST_INSTALL_DIR)/extensions/indexes/lucene/lib/lucene.hebrew.jar 

$(EXIST_INSTALL_DIR)/extensions/indexes/lucene/lib/lucene.hebrew.jar:
	cp $(LIBDIR)/hebmorph/java/lucene.hebrew/build/distribution/lucene.hebrew.jar $(EXIST_INSTALL_DIR)/extensions/indexes/lucene/lib

copy-files:
	$(SETUPDIR)/makedb.py -h $(EXIST_INSTALL_DIR) -p 775 -d 775 -q 755 $(DBDIR)
	@echo "Copying files to database..."
	@#copy the transliteration DTD first so eXist will know where they are during restore 
	cp $(SETUPDIR)/opensiddur-catalog.xml $(EXIST_INSTALL_DIR)/webapp/WEB-INF
	cp $(SETUPDIR)/hebrew.dtd $(EXIST_INSTALL_DIR)/webapp/WEB-INF/entities
	$(EXISTBACKUP) -r `pwd`/$(DBDIR)/__contents__.xml -ouri=xmldb:exist:// -p "$(ADMINPASSWORD)"

.PHONY: setup-password setup-clean
setup-password: $(SETUPDIR)/setup.xql

setup-clean: 
	rm -f $(SETUPDIR)/setup.xql

$(SETUPDIR)/setup.xql:
	@echo "Setting admin password to the value in the Makefile. You did change it Makefile.local, right?..." && \
		cat $(SETUPDIR)/setup.tmpl.xql | sed "s/ADMINPASSWORD/$(ADMINPASSWORD)/g" > $(SETUPDIR)/setup.xql && \
		echo "done."
	$(EXISTCLIENT) -qls -u admin -P "$(ADMINPASSWORD)" -F $(SETUPDIR)/setup.xql
	rm -f $(SETUPDIR)/setup.xql

#$(EXIST_INSTALL_DIR)/EXIST.AUTOINSTALLED: 
#	make db-install

# install the WLC files into $WLCDBDIR on the database and assure that they're
# ready to be used (note: may overwrite existing files, use with caution)
# reference index not being used yet, so ridx-disable/enable are disabled
db-install-wlc: tanach tanach2db 

.PHONY: tanach2db
tanach2db:
	$(SETUPDIR)/makedb.py -h $(EXIST_INSTALL_DIR) -p 774 -d 775 -c /db/data -u admin -g everyone $(TEXTDIR)/wlc
	$(EXISTBACKUP) -r `pwd`/$(WLC-OUTPUT-DIR)/__contents__.xml -u admin -p "$(ADMINPASSWORD)" -ouri=xmldb:exist://

db-syncclean:
	for f in `find . -name __contents__.xml`; do rm "$$f"; done

db-uninstall:
	@echo "WARNING: This will remove the copy of eXist in $(EXIST_INSTALL_DIR) within 10s. If you do not want to do that, cancel now with ctrl-c!!!!" && \
	sleep 10 && \
	echo "too late." && \
	rm -fr $(EXIST_INSTALL_DIR)

# synchronize the contents of the development directories to a running db
# (a bit of a misnomer, since it will not delete files from the db!)
db-sync:
	$(SETUPDIR)/makedb.py -h $(EXIST_INSTALL_DIR) -p 755 -c /db/code $(CODEDIR) 
	$(SETUPDIR)/makedb.py -h $(EXIST_INSTALL_DIR) -p 775 -g everyone -c /db/data $(DATADIR) 
	$(SETUPDIR)/makedb.py -h $(EXIST_INSTALL_DIR) -p 755 -c /db/common $(COMMONDIR) 
	$(EXISTBACKUP) -u admin -p $(DBAPASS) -r `pwd`/$(CODEDIR)/__contents__.xml -ouri=xmldb:exist://localhost:8080/xmlrpc
	$(EXISTBACKUP) -u admin -p $(DBAPASS) -r `pwd`/$(DATADIR)/__contents__.xml -ouri=xmldb:exist://localhost:8080/xmlrpc
	$(EXISTBACKUP) -u admin -p $(DBAPASS) -r `pwd`/$(COMMONDIR)/__contents__.xml -ouri=xmldb:exist://localhost:8080/xmlrpc

.PHONY: db db-nonet
db: externals db-nonet

# patch error status ignored because it returns 1 if patches are already applied
db-nonet: schema transforms $(DBDIR)/code $(DBDIR)/common 
	mkdir -p $(DBDIR)/xforms
	rsync $(RSYNC_EXCLUDE) -a --delete $(LIBDIR)/xsltforms/trunk/build/ $(DBDIR)/xforms/xsltforms
	rsync $(RSYNC_EXCLUDE) -a --delete $(LIBDIR)/xspec $(DBDIR)/code/modules/resources
	rsync $(RSYNC_EXCLUDE) -a --delete data $(DBDIR)
	cp $(CODEDIR)/common/params.xsl2 $(DBDIR)/code/common	
	#-patch -p1 -Nr - < $(SETUPDIR)/generate-common-tests.xsl.patch
	#-patch -p1 -Nr - < $(SETUPDIR)/generate-tests-utils.xsl.patch
	#-patch -p1 -Nr - < $(SETUPDIR)/generate-xspec-tests.xsl.patch

db-clean:
	rm -fr $(DBDIR)/schema $(DBDIR)/code $(DBDIR)/data $(DBDIR)/common $(DBDIR)/cache

# equivalent of svn externals
.PHONY: db-externals

.PHONY: externals submodules
externals: svn-xspec svn-xsltforms svn-xsltdoc svn-tei svn-exist

submodules:
	git submodule init
	git submodule update

.PHONY: svn-xspec svn-xsltforms svn-xsltdoc svn-tei svn-exist
svn-xspec: $(XSPECDIR)
	svn update $(XSPECDIR)

$(XSPECDIR):
	svn co $(XSPECREPO) $(XSPECDIR)

svn-xsltforms: $(XSLTFORMSDIR)
	svn update $(XSLTFORMS_REVISION) $(XSLTFORMSDIR)

$(XSLTFORMSDIR):
	svn co $(XSLTFORMS_REVISION) $(XSLTFORMSREPO) $(XSLTFORMSDIR)

svn-xsltdoc: $(XSLTDOCDIR)
	svn update $(XSLTDOCDIR)

$(XSLTDOCDIR):
	svn co $(XSLTDOCREPO) $(XSLTDOCDIR)

svn-tei: $(TEIDIR)
	svn update $(TEI_REVISION) $(TEIDIR)

$(TEIDIR):
	svn co $(TEIREPO) $(TEIDIR)

svn-exist: $(EXISTSRCDIR)
	svn update $(EXIST_REVISION) $(EXISTSRCDIR)

$(EXISTSRCDIR):
	svn co $(EXIST_REVISION) $(EXISTSRCREPO) $(EXISTSRCDIR)

.PHONY: ridx-enable ridx-disable
ridx-enable:
	@echo Re-enabling the index and indexing database references. This may take a while...
	$(EXISTCLIENT) -u admin -P "$(ADMINPASSWORD)" -qls -F $(SETUPDIR)/enable-refindex.xql
	$(EXISTCLIENT) -qls -u admin -P "$(ADMINPASSWORD)" -F $(SETUPDIR)/reindex-refindex.xql

ridx-disable:
	$(EXISTCLIENT) -u admin -P "$(ADMINPASSWORD)" -qls -F $(SETUPDIR)/disable-refindex.xql

