#!/bin/sh
# canonicalize directory script
#
# Licensed under Creative Commons Attribution-ShareAlike version 2.5 
# <http://creativecommons.org/licenses/by-sa/2.5/>
# Written by user Keith Smith <http://stackoverflow.com/users/12347/keith-smith> on 
# Stack Overflow
# <http://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac>
# $Id: absolutize 427 2010-01-17 02:25:46Z efraim.feinstein $
TARGET_FILE=$1

cd `dirname $TARGET_FILE`
TARGET_FILE=`basename $TARGET_FILE`

# Iterate down a (possible) chain of symlinks
while [ -L "$TARGET_FILE" ]
do
    TARGET_FILE=`readlink $TARGET_FILE`
    cd `dirname $TARGET_FILE`
    TARGET_FILE=`basename $TARGET_FILE`
done

# Compute the canonicalized name by finding the physical path 
# for the directory we're in and appending the target file.
PHYS_DIR=`pwd -P`
RESULT=$PHYS_DIR/$TARGET_FILE
echo $RESULT
