#!/bin/sh
echo This is not a real XeLaTeX. It is a placeholder because XeLaTeX is required by the TEI software, even though we do not use the functionality.
echo If you have real XeLaTeX, it should be in the PATH before this one.
