#!/usr/bin/env python
# Extract the outline (table of contents) from the PDF.
# For the 1917 JPS PDF extraction project for the Open Siddur Project.
# Copyright 2011-12 Marc Stober and licensed under the terms of the LGPL
# WORK IN PROGRESS !!!

import os.path
import sys
from pdfminer.pdfparser import PDFParser, PDFDocument

fp = open('Tanakh-JPS1917.pdf', 'rb')
parser = PDFParser(fp)
doc = PDFDocument()
parser.set_document(doc)
doc.set_parser(parser)
#doc.initialize(password)

outp_path = 'toc.txt'
print('Generating "%s"...' % outp_path)
outp = open(outp_path, 'w')
outp.write('# Generated by %s\n' % os.path.split(sys.argv[0])[1])

# Get the page numbers for the page object ID's.
p = 0
pageNumbers = {}
for page in doc.get_pages():
	p += 1
	pageNumbers[page.pageid] = p

# Get the outlines of the document.
outlines = doc.get_outlines()
for (level,title,dest,a,se) in outlines:
	title = title.replace(chr(10), '').replace(chr(13), '').strip()
	# Get the destination page number from the action.
	# Thanks to https://groups.google.com/d/topic/pdfminer-users/KwMJHZTCKbE/discussion
	pageid = a.resolve()['D'][0].objid
	outp.write(' '.join((level * ' ', title, str(pageNumbers[pageid]), '\n')))
	#import pdb; pdb.set_trace()

outp.close()



