# Deployment to Google Compute Engine
name: CI/CD pipeline for GCE

on:
  push:
    branches:
      - master
      - develop
      - feature**

env:
  PROJECT_NAME: opensiddur-client
  VERSION: ${{GITHUB_SHA:0:8}}
  BRANCH: ${{GITHUB_REF#refs/heads/}}
  INSTANCE_BASE: ${{PROJECT_NAME}}-${{BRANCH//\//-}}
  INSTANCE_NAME: ${{INSTANCE_BASE}}-${{VERSION}}
  BACKUP_BUCKET_BASE: opensiddur-database-backups
  ZONE: us-west2-a
  MACHINE_TYPE: n1-standard-1
  IMAGE_PROJECT: ubuntu-os-cloud
  IMAGE_VERSION: ubuntu-2004
  BOOT_DISK_SIZE_GB: 20
  EXIST_MEMORY: 3072
  STACK_MEMORY: 512
  SERVICE_ACCOUNT: opensiddur-deploy-1@opensiddur-client.iam.gserviceaccount.com
  ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
  DYN_USERNAME: ${{ secrets.DYN_USERNAME }}
  DYN_PASSWORD: ${{ secrets.DYN_PASSWORD }}
  DYN_EMAIL: ${{ secrets.DYN_EMAIL }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GCE_SA_KEY }}
          project_id: ${{ PROJECT_NAME }}

      - run: |-
          gcloud --quiet auth
      - name: Build
        run: |-
          ant test
      - name: Deploy
        run: |-
          gcloud compute \
                --project=${PROJECT_NAME} instances create ${INSTANCE_NAME} \
                --zone=${ZONE} \
                --machine-type=${MACHINE_TYPE} \
                --network=default \
                --network-tier=PREMIUM \
                --maintenance-policy=MIGRATE \
                --scopes=https://www.googleapis.com/auth/cloud-platform \
                --tags=http-server,https-server \
                --image=$(gcloud compute images list --filter=${IMAGE_PROJECT} --filter=${IMAGE_VERSION} | tail -n 1 | cut -f 1 -d " ") \
                --image-project=${IMAGE_PROJECT} \
                --boot-disk-size=${BOOT_DISK_SIZE_GB}GB \
                --boot-disk-type=pd-standard \
                --boot-disk-device-name=${INSTANCE_NAME} \
                --service-account=${SERVICE_ACCOUNT} \
                --metadata-from-file startup-script=setup/gcloud-startup-script.sh \
                --metadata ADMIN_PASSWORD=${ADMIN_PASSWORD},EXIST_MEMORY=${EXIST_MEMORY},STACK_MEMORY=${STACK_MEMORY},BRANCH=${BRANCH},DYN_USERNAME=${DYN_USERNAME},DYN_PASSWORD=${DYN_PASSWORD},DYN_EMAIL=${DYN_EMAIL},BACKUP_BUCKET_BASE=${BACKUP_BUCKET_BASE},enable-oslogin=true


